version: MAIR++

mode: AlbedoFusion

nepoch: 10
batchsize: 8
num_workers: 4
use_checkpoint: False
#use_checkpoint: True

#eval_format: [test, step, 3000]
eval_format: [ test, epoch, 1 ]

losskey: [ a, ]
losstype: [ sil2, ]
weight: [ 1.0, ]
lossmask: [ mask,  ]

scheduler:
  init_lr: 5e-4
  type: OneCycleLR
  max_lr: 2e-3
  final_lr: 2e-4

ContextNet:
  path: 04151435_BRDF
  use: True
  net_in: [ rgb, n, d ]
  dim: 32
  norm: batch

AggregationNet:
  path: 04151435_BRDF
  spec_type: 'spec_in'

  light_hidden: 128
  refdir_in: False
  light_dim: 64

  out_dim: 32
  out_hidden: 128

  type: mva_attn
  depth: 2
  dim_head: 32
  mlp_hidden: 128
  target_embed: True
  attn_dim_head: 16
  attn_n_head: 4

RefineNet:
  path: 04151435_BRDF
  type: old
  net_in: [ rgb, n, d, brdf_feat ]
  #  filters: [ 64, 128, 256, 512 ]
  norm: group

AlbedoFusion:
  use: True

imWidth: 320
imHeight: 240
e_type: e
envCols: 160
envRows: 120
env_height: 8
env_width: 16
num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_print: 10
i_record: 50
d_type: net

MGNet:
  path: 02161212_MG
  init_feature: 96

InLightEncoder:
  path: 02261143_incident
  init_feature: 64
  dim: 96

ShadingNet:
  path: 02261143_incident
  mlp_init: True
  hidden: 128
  num_layers: 3
  last_bias: False

SpecularNet:
  path: 02261143_incident
  mlp_init: True
  hidden: 128
  num_layers: 4
  last_bias: False