version: MAIR

mode: BRDF

nepoch: 10
batchsize: 8
num_workers: 4
use_checkpoint: False
#use_checkpoint: True

#eval_format: [test, step, 3000]
eval_format: [ test, epoch, 1 ]

losskey: [ a, r ]
losstype: [ sil2, l2 ]
weight: [ 3.0, 1.0 ]
lossmask: [ mask, mask ]

scheduler:
  init_lr: 1e-3
  type: OneCycleLR
  max_lr: 1e-3
  final_lr: 1e-3

ContextNet:
  use: True
  net_in: [rgb, n, d, c]
  dim: 32
  norm: batch

AggregationNet:
  DL_type: microfacet
  light_mix: cat

  light_hidden: 32
  light_dim: 8

  out_dim: 32
  out_hidden: 128

  type: mva
  dim_head: 32
  depth: 2
  mlp_hidden: 128

RefineNet:
  use: True
  net_in: [rgb, n, d, c, brdf_feat]
  type: old
  norm: group

imWidth: 320
imHeight: 240
e_type: e
envCols: 120
envRows: 160
env_height: 8
env_width: 16
num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_print: 10
i_record: 50
d_type: cds

MGNet:
  path: 02161212_MG
  init_feature: 96

InLightSG:
  path: 04041720_incident_org
  SGNum: 3
  init_feature: 64
  e_type: e_d
