version: MAIR++

mode: BRDF

nepoch: 10
batchsize: 4
accum_iter: 2
#batchsize: 8
#accum_iter: 1
num_workers: 4
use_checkpoint: False
#use_checkpoint: True

#eval_format: [test, step, 3000]
eval_format: [ test, epoch, 1 ]

losskey: [ a, r ]
losstype: [ sil2, l2 ]
weight: [ 3.0, 1.0 ]
lossmask: [ mask, mask ]

scheduler:
  type: OneCycleLR
  init_lr: 6e-4
  max_lr: 3e-3
  final_lr: 5e-4

ContextNet:
  use: True
  net_in: [rgb, n, d]
  dim: 32
  norm: batch

AggregationNet:
  DL_type: microfacet
  light_mix: cat

  light_hidden: 32
  light_dim: 8

  out_dim: 32
  out_hidden: 128

  type: mva_attn
  depth: 2
  dim_head: 32
  mlp_hidden: 128
  target_embed: True
  attn_dim_head: 16
  attn_n_head: 4

RefineNet:
  type: old
  net_in: [rgb, n, d, brdf_feat]
#  filters: [ 64, 128, 256, 512 ]
  norm: group

imWidth: 320
imHeight: 240
e_type: e
envCols: 160
envRows: 120
env_height: 8
env_width: 16
num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_print: 10
i_record: 50
d_type: net

MGNet:
  path: 02161212_MG
  init_feature: 96

InLightSG:
  path: 03180132_incident
  init_feature: 64
  SGNum: 12