version: MAIR++

mode: BRDF

nepoch: 10
batchsize: 8
accum_iter: 4
num_workers: 4
use_checkpoint: False
#use_checkpoint: True

#eval_format: [test, step, 3000]
eval_format: [ test, epoch, 1 ]

losskey: [ a, r ]
losstype: [ sil2, l2 ]
weight: [ 3.0, 1.0 ]
lossmask: [ mask, mask ]

scheduler:
  type: OneCycleLR
  init_lr: 1e-3
  max_lr: 1e-3
  final_lr: 1e-3

ContextNet:
  use: True
  net_in: [ rgb, n, d ]
  dim: 32
  norm: batch

AggregationNet:
  spec_type: 'spec_in'

  light_hidden: 128
  refdir_in: False
  light_dim: 64

  out_dim: 32
  out_hidden: 128

  attn_type: None
  type: mva
  dim_head: 32
  depth: 2
  mlp_hidden: 128

RefineNet:
  type: old
  net_in: [ rgb, n, d, brdf_feat ]
  #  filters: [ 64, 128, 256, 512 ]
  norm: group

imWidth: 320
imHeight: 240
e_type: e
envCols: 160
envRows: 120
env_height: 8
env_width: 16
num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_print: 10
i_record: 50
d_type: net

MGNet:
  path: 02161212_MG
  init_feature: 96

InLightEncoder:
  path: 02261143_incident
  init_feature: 64
  dim: 96

ShadingNet:
  path: 02261143_incident
  mlp_init: True
  hidden: 128
  num_layers: 3
  last_bias: False

SpecularNet:
  path: 02261143_incident
  mlp_init: True
  hidden: 128
  num_layers: 4
  last_bias: False