version: MAIR

mode: incident

nepoch: 20
batchsize: 16 # for training
num_workers: 4
eval_format: [ test, epoch, 1 ]

losskey: [ e_d, e_d, vis]
losstype: [ silogl2, logl2, beta]
weight: [ 1.0, 1.0,  0.001]
lossmask: [ mask, mask, mask]
si_ramp: 10000
si_max: 100

scheduler:
  init_lr: 1e-4
  type: OneCycleLR
  max_lr: 5e-4
  final_lr: 5e-5

MGNet:
  path: 02161212_MG
  init_feature: 96

InLightSG:
  SGNum: 3
  init_feature: 64

imWidth: 320
imHeight: 240
e_type: e_d
envCols: 40
envRows: 30
env_height: 8
env_width: 16
num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_print: 10
i_record: 50
#d_type: net
d_type: cds
