version: MAIR++

#scene_name: E:/oi_scene_output2024/{}/data4_apples_014
#scene_name: /media/vig-titan-118/Samsung_T5/oi_scene_output2024/{}/howardzhou_064_tufted_chair_034
scene_name: /media/vig-titan-118/Samsung_T5/oi_scene_output2024/{}/qq3_022
#scene_name: E:/oi_scene_output2024/{}/howardzhou_064_tufted_chair_034
mode: mat_edit
models: [ Li21, Zhu, MAIR, MAIR++ ]
#models: [ Li21, MAIR, MAIR++ ]
#models: [ Zhu, MAIR++ ]


a_permute: [0, 1, 2]
#a_permute: [0, 2, 1]
#a_permute: [1, 2, 0]
#a_permute: [1, 0, 2]
#a_permute: [ 2, 0, 1 ]
#a_permute: [2, 1, 0]

a_scale: [ 0.8, 0.6, 1.2 ]
#a_scale: [ 0.1, 3.5, 0.0 ]
#a_scale: [ 0., 0., 0. ]

a_offset: [0., 0., 0.]
#a_offset: [ 0.6, 0.1, 0.15 ]

#r_edit: None
r_edit: 1.0

batchsize: 1
num_workers: 1

InLightEncoder:
  path: 02261143_incident
#  path: 05261838_incident
  init_feature: 64
  dim: 96

ShadingNet:
  path: 02261143_incident
#  path: 05261838_incident
  mlp_init: True
  hidden: 128
  num_layers: 3
  last_bias: False

SpecularNet:
  path: 02261143_incident
#  path: 05261838_incident
  mlp_init: True
  hidden: 128
  num_layers: 4
  last_bias: False

imWidth: 320
imHeight: 240
e_type: e
envCols: 160
envRows: 120
env_height: 8
env_width: 16
num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_print: 10
i_record: 50
d_type: net
